baseURL = 'https://auteur.ing'
languageCode = 'en-us'
title = 'auteuring'
theme = 'hugo-book'

[params]
  BookToC = true
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookSection = "/"
  BookTheme = 'auto'

[markup]
  [markup.tableOfContents]
    endLevel = 8
    ordered = false
    startLevel = 1

  [markup.goldmark.renderer]
  unsafe = true

[menu]
[[menu.after]]
  name = "குரல் (kural)"
  url = "https://kural.auteur.ing"
  weight = 10 