baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'auteuring'
theme = 'hugo-book'

[params]
  BookToC = true
  BookDateFormat = 'Jan 2, 2006'
  BookSearch = true
  BookSection = "docs"

[markup]
  [markup.tableOfContents]
    endLevel = 8
    ordered = false
    startLevel = 1

  [markup.goldmark.renderer]
  unsafe = true 